# Generated by Django 6.1.1 on 2026-09-22 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('capacity_leaders', models.PositiveIntegerField(default=15)),
                ('capacity_followers', models.PositiveIntegerField(default=15)),
                ('rsvp_deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('follower', 'Follower'), ('both', 'Entrambi')], default='leader', max_length=10)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzato')], default='intermediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Presente'), ('not_attending', 'Assente'), ('waitlisted', "In Lista d'Attesa")], default='attending', max_length=20)),
                ('role_for_event', models.CharField(blank=True, choices=[('leader', 'Leader'), ('follower', 'Follower'), ('both', 'Entrambi')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.participant')),
            ],
            options={
                'unique_together': {('participant', 'event')},
            },
        ),
    ]
