# Generated by Django 6.1.1 on 2026-09-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagetemplate_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rotation', models.BooleanField(default=False, help_text='True se questa persona è in rotazione a causa di disparità numerica.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.event')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_matches', to='core.participant')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_matches', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
