# Generated by Django 6.1.1 on 2026-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_group_name',
            field=models.CharField(default='Tango Catango', help_text='Nome esatto del gruppo WhatsApp in cui inviare i messaggi', max_length=200),
        ),
    ]
