# Generated by Django 6.1.1 on 2026-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_whatsapp_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='match_send_at',
            field=models.DateTimeField(blank=True, help_text='Data e ora in cui inviare il messaggio con le coppie definitive', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_sent',
            field=models.BooleanField(default=False, help_text='Flag impostato a True quando le coppie sono state inviate'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_send_at',
            field=models.DateTimeField(blank=True, help_text='Data e ora in cui inviare il messaggio di apertura adesioni', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_sent',
            field=models.BooleanField(default=False, help_text='Flag impostato a True quando il messaggio adesioni è stato inviato'),
        ),
    ]
