# Generated by Django 6.1.1 on 2026-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_match_send_at_event_match_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], default=0, help_text="Giorno della settimana in cui si tiene l'evento")),
                ('time', models.TimeField(help_text="Ora in cui inizia l'evento")),
                ('start_date', models.DateField(help_text='Data a partire dalla quale iniziare a schedulare')),
                ('rsvp_days_before', models.IntegerField(default=5, help_text="Quanti giorni prima dell'evento inviare il sondaggio WhatsApp")),
                ('rsvp_time', models.TimeField(help_text='A che ora inviare il sondaggio')),
                ('match_days_before', models.IntegerField(default=1, help_text="Quanti giorni prima dell'evento chiudere le adesioni e inviare le coppie")),
                ('match_time', models.TimeField(help_text='A che ora generare e inviare le coppie')),
            ],
        ),
    ]
