# Generated by Django 6.1.1 on 2026-09-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recurringschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringschedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='days_of_week',
            field=models.CharField(default='0', help_text='Giorni della settimana (0=Lunedì, 6=Domenica) separati da virgola', max_length=50),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Data fine schedulazione', null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='match_days_before',
            field=models.IntegerField(default=0, help_text="Quanti giorni prima dell'evento chiudere le adesioni e inviare le coppie"),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='match_time',
            field=models.TimeField(blank=True, help_text='A che ora generare e inviare le coppie', null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='rsvp_days_before',
            field=models.IntegerField(default=0, help_text="Quanti giorni prima dell'evento inviare il sondaggio WhatsApp"),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='rsvp_time',
            field=models.TimeField(blank=True, help_text='A che ora inviare il sondaggio', null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='start_date',
            field=models.DateField(blank=True, help_text='Data a partire dalla quale iniziare a schedulare', null=True),
        ),
    ]
