# Generated by Django 6.1.1 on 2026-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_recurringschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Chiave API per Google Gemini (Lettura Chat)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='match_time',
            field=models.TimeField(default='19:00:00', help_text='Ora di chiusura adesioni e invio coppie'),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='rsvp_days_before',
            field=models.IntegerField(default=0, help_text="Giorni prima dell'evento in cui inviare l'annuncio"),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='rsvp_time',
            field=models.TimeField(default='08:00:00', help_text="Ora in cui inviare l'annuncio (es. mattina)"),
        ),
    ]
