# Generated by Django 6.1.1 on 2026-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recurringschedule_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='debug_mode',
            field=models.BooleanField(default=True, help_text='Mostra o nascondi i log delle attività'),
        ),
    ]
