# Generated by Django 6.1.1 on 2026-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recurringschedule_debug_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='rsvp_mode',
            field=models.CharField(choices=[('POLL', 'Sondaggio (Default)'), ('LLM', 'Risposta Libera (Gemini AI)')], default='POLL', help_text='Modalità di raccolta adesioni', max_length=10),
        ),
    ]
