# Generated by Django 6.1.1 on 2026-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurringschedule_rsvp_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Uomo'), ('F', 'Donna')], default='M', max_length=1),
        ),
    ]
